sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.sourceEncoding=UTF-8

# sonar.exclusions=
# sonar.inclusions=
# sonar.test.exclusions=
# sonar.test.inclusions=
# sonar.cpd.exclusions=
