ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ kz.global.api.ApplicationKt.module ]
    }
}

database {
    url = ${DATABASE_URL}
    maximumPoolSize = 10
    maximumPoolSize = ${?DATABASE_POOL_SIZE}
}

r2 {
    endpoint = ${R2_ENDPOINT}
    accessKeyId = ${R2_ACCESS_KEY_ID}
    secretAccessKey = ${R2_SECRET_ACCESS_KEY}
    bucket = ${R2_BUCKET}
}

admin {
    bearerKey = ${ADMIN_BEARER_KEY}
}
